[workspace]
members = [
    "apps/*"
]

[workspace.dependencies]
aes = "^0.8"
aes-gcm-siv = "^0.11"
crypto = "^0.4"
generic-array = "^0.14"
hex = "^0.4"
rand = "^0.8"
scrypt = {version = "^0.10"}
sha3 = {version = "^0.10"}
